### ISSUE TITLE
turnstile

### ISSUE THREAD

**Issue by arturstrong1** [AkashiCoin/captcha-api#2]
INFO:     185.100.232.44:50486 - "POST /token/turnstile/solve HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\captcha-api-master\router\turnstile.py", line 39, in solve
    return make_response(token, end_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\captcha-api-master\router\utils.py", line 13, in make_response
    return CaptchaResponse(status="error", token="")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for CaptchaResponse
time
  Field required [type=missing, input_value={'status': 'error', 'token': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

**Comment by arturstrong1** [comment]
I solved this problem
pip install unicorn

**Comment by arturstrong1** [comment]
2024-04-08 12:41:33.679 | INFO     | router.turnstile:solve:38 - took 30.95332431793213 seconds :: failed
INFO:     185.100.232.44:50894 - "POST /token/turnstile/solve HTTP/1.1" 200 OK
INFO:     185.100.232.44:50914 - "GET /docs HTTP/1.1" 200 OK
INFO:     185.100.232.44:50914 - "GET /openapi.json HTTP/1.1" 200 OK
2024-04-08 12:42:35.505 | INFO     | router.turnstile:solve:38 - took 28.08989143371582 seconds :: failed
INFO:     185.100.232.44:50915 - "POST /token/turnstile/solve HTTP/1.1" 200 OK
2024-04-08 12:43:38.072 | INFO     | router.turnstile:solve:38 - took 33.00323462486267 seconds :: failed
INFO:     188.208.196.101:54686 - "POST /token/turnstile/solve HTTP/1.1" 200 OK


but I can't solve the captcha

**Comment by arturstrong1** [comment]
this problem was also solved, it was in a proxy

**Comment by arturstrong1** [comment]
INFO:      - "POST /token/turnstile/solve HTTP/1.1" 200 OK
Task exception was never retrieved
future: <Task finished name='Task-389' coro=<Response.finished.<locals>.on_finished() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_network.py:586> exception=Error('Target closed')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_network.py", line 588, in on_finished
    raise Error("Target closed")
playwright._impl._errors.Error: Target closed

Is this how it should be?
